
exports.inicio = (d) => {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores e Periodos Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositores e Periodos Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Escolha uma opção:</legend>
                        <li><a href='/compositores'>Compositores</a></li>
                        <li><a href='/periodos'>Periodos</a></li>
                    </fieldset>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}


exports.compositoreslistPage = (slist, d) => {
    var pagHTML = `
        <!DOCTYPE html>
        <html>    
            <head>
                <meta charset="UTF-8">
                <link rel="icon" href="favicon.png">
                <link rel="stylesheet" href="w3.css">
                <title>Gestão de compositores</title>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-teal">
                        <h1>Lista de compositores
                        <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                        </h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>bio</th>
                                <th>Data de Nascimento</th>
                                <th>Data Obito</th>
                                <th>Periodo</th>
                                <th>Actions</th>
                            </tr>
    `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
            <tr>
                <td>
                    ${slist[i].id}
                </td>
                <td>
                    <a href="/compositores/${slist[i].id}"> 
                        ${slist[i].nome} 
                    </a>
                </td>
                <td>
                    ${slist[i].bio}
                </td>
                <td>
                ${slist[i].dataNasc}
                </td>
                <td>
                ${slist[i].dataObito}
                </td>
                <td>
                    ${slist[i].periodo}
                </td>
                <td>
                    [<a href="/compositores/edit/${slist[i].id}">Editar</a>]
                    [<a href="/compositores/delete/${slist[i].id}">Eliminar</a>]
                </td>
            </tr>
        `
    }
    pagHTML += `
                        </table>
                    </div>
                        
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </body>
        </html>
    `

    return pagHTML
}


exports.periodoslistPage = (slist, d) => {
    var pagHTML = `
        <!DOCTYPE html>
        <html>    
            <head>
                <meta charset="UTF-8">
                <link rel="icon" href="favicon.png">
                <link rel="stylesheet" href="w3.css">
                <title>Gestão de periodos</title>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-teal">
                        <h1>Lista de periodos
                        <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                        </h1>
                    </header>

                    <div class="w3-container">
                        <table class="w3-table-all">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                
                            </tr>
    `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
            <tr>
                <td>
                    ${slist[i].id}
                </td>
                <td>
                    <a href="/periodos/${slist[i].id}"> 
                        ${slist[i].nome} 
                    </a>
                </td>
                
                <td>
                    [<a href="/periodos/edit/${slist[i].id}">Editar</a>]
                    [<a href="/periodos/delete/${slist[i].id}">Eliminar</a>]
                </td>
            </tr>
        `
    }
    pagHTML += `
                        </table>
                    </div>
                        
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </body>
        </html>
    `

    return pagHTML
}

exports.compositoresFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositores Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>DData Obito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>periodos Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodos Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>DETALHES</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        </fieldset>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.compositoresConsultPage = function(compositor,d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositores Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Detalhes:</legend>
                        <label>Compositor ID: ${compositor.id}</label><br>
                        <label>Name: ${compositor.nome}</label><br>
                        <label>Bio: ${compositor.bio}</label><br>
                        <label>Data de Nascimento: ${compositor.dataNasc}</label><br>
                        <label>Data de Óbito: ${compositor.dataObito}</label><br>
                        <label>Periodo: ${compositor.periodo}</label><br>
                    </fieldset>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.periodosConsultPage = function(periodo,d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodos Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Detalhes:</legend>
                        <label>Compositor ID: ${periodo.id}</label><br>
                        <label>Name: ${periodo.nome}</label><br>
                    
                    </fieldset>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.compositoresDeletePage = function(compositor,d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Delete Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h2>Delete Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST" action="/compositores/delete/${compositor.id}?_method=DELETE">
                    <fieldset>
                        <legend>Are you sure you want to delete this compositor?</legend>
                        <label>Compositor ID: ${compositor.id}</label>
                        <label>Name: ${compositor.nome}</label>
                        <label>Bio: ${compositor.bio}</label>
                        <label>Data de Nascimento: ${compositor.dataNasc}</label>
                        <label>Data de Óbito: ${compositor.dataObito}</label>
                        <label>Periodo: ${compositor.periodo}</label>
                    </fieldset>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Delete</button>
                    <a href="/" class="w3-btn w3-purple w3-mb-2">Cancel</a>
                </form>

                <footer class="w3-container w3-red">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.periodoDeletePage = function(periodo,d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Delete Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h2>Delete Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST" action="/periodos/delete/${periodo.id}?_method=DELETE">
                    <fieldset>
                        <legend>Are you sure you want to delete this compositor?</legend>
                        <label>Periodo ID: ${periodo.id}</label>
                        <label>Name: ${periodo.nome}</label>
                    </fieldset>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Delete</button>
                    <a href="/" class="w3-btn w3-purple w3-mb-2">Cancel</a>
                </form>

                <footer class="w3-container w3-red">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        <body>
    `
}

exports.compositoresFormEditPage = function(a, d){
    console.log(a) 
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositores Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>Data de nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${a.dataNasc}"/>
                        <label>Data Obito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${a.dataObito}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


exports.periodoFormEditPage = function(a, d){
    console.log(a) 
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>periodo Form</h2>
                </header>
            
                <form class="w3-container" method="POST" >
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.studentPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Número: </b> ${compositor.id}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por compositor::RPCW2022 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}